### ISSUE TITLE
Windows 10 22H2 19045.3803 安装indirect display出现屏幕反复闪烁问题

### ISSUE THREAD

**Issue by sudo-000** [fanxiushu/xdisp_virt#23]
系统版本 Windows 10 22H2 Build 19045.3803
已破解Driver Signature Enforcement，除虚拟显示器以外其他驱动均能正常加载。
测试环境VMware Workstation Pro 16.2.3

表现：安装驱动没有问题，但是一旦ini配置文件中填上了Enable=1就开始亮一下黑一下亮一下黑一下亮一下黑一下

**Comment by sudo-000** [comment]
已找到问题关键：
是虚拟显示器驱动与VMware的显卡发生冲突导致的，实体机上安装没事的。
虚拟机里卸载掉VMware Tools也可以正常运行。

希望以后能增强一下对虚拟机显卡的适配，谢谢。

**Comment by fanxiushu** [comment]
如图，我的vmware没啥问题，当然vmware版本是17.5.1，最新版本的vmware，
vmware对显卡支持不够好，或者与宿主机有些冲突。

**Comment by fanxiushu** [comment]
![Uploading vmware-IDD.jpg…]()

**Comment by happymimimix** [comment]
> 我的vmware没啥问题，当然vmware版本是17.5.1，最新版本的vmware， vmware对显卡支持不够好，或者与宿主机有些冲突。

我用的16
