### ISSUE TITLE
Rustdesk v1.3，开启隐私模式，模式2时，提示: 不支持 Indirect display driver 。需要 Windows 10 版本 2004 及更高的版本。

### ISSUE THREAD

**Issue by tqangxl** [fanxiushu/xdisp_virt#30]
系统win2019
![image](https://github.com/user-attachments/assets/7b47fd55-a993-4eaf-9839-d56896bd839f)

![image](https://github.com/user-attachments/assets/fe43250e-6eb4-4d4e-89ab-56d9013ac70c)
可以添加下2004版本  兼容吗？谢谢大牛
![image](https://github.com/user-attachments/assets/7058b9f0-db67-46e3-adac-920c8177f9ca)

**Comment by fanxiushu** [comment]
你搞错项目地址了，这里是xdisp_virt，不是你说的rustdesk，我也没用过这玩意，
请使用过xdisp_virt之后再来提问！
